[[language]]
name = "python"
language-servers = ["basedpyright", "ruff"]
auto-format = true
formatter = { command = "./.venv/bin/ruff", args = ["format", "-"] }

[language-server.basedpyright]
command = "./.venv/bin/basedpyright-langserver"
args = ["--stdio"]

[language-server.basedpyright.config.basedpyright.analysis]
typeCheckingMode = "off"
autoImportCompletions = true

[language-server.ruff]
command = "./.venv/bin/ruff"
args = ["server"]
